version: '3'

services:
  mysqldb:
    image: mysql:8.0
    networks:
      - tpfoyer-network
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=tpfoyer
    restart: unless-stopped

  tpfoyer:
    image: zaougaeya/tpfoyer:etudiant
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/tpfoyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "rootpass"
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    networks:
      - tpfoyer-network
    stdin_open: true
    tty: true

  sonarqube:
    image: sonarqube:community
    ports:
      - "9002:9002"
    networks:
      - sonarnet
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  nexus:
    image: sonatype/nexus3
    ports:
      - "8082:8082"
    networks:
      - sonarnet
    volumes:
      - nexus-data:/nexus-data

  prometheus:
    image: prom/prometheus
    ports:
      - "9093:9093"
    networks:
      - monitoring-net
    volumes:
      - prometheus_data:/etc/prometheus

networks:
  sonarnet:
  tpfoyer-network:
    driver: bridge
  monitoring-net:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  nexus-data:
  prometheus_data:
